### ISSUE TITLE
get lf to show the icons for the file-type?

### ISSUE THREAD

**Issue by joamatab** [BrodieRobertson/dotfiles#1]
thank you for your Youtube videos Brodie!

thanks to you I switched to `lsd`

![image](https://user-images.githubusercontent.com/4514346/67068462-00c24780-f12f-11e9-826e-35143399d839.png)

and now i get nice icons ^^

How do you get lf to show the icons for the file-type?
this is the config that I use https://github.com/joamatab/dotfiles/blob/master/lf/lfrc

here is a screenshot of the `lf` view

![image](https://user-images.githubusercontent.com/4514346/67068307-81347880-f12e-11e9-8331-3570adfabf8d.png)

**Comment by maxdevjs** [comment]
@joamatab if you did not already solved it, look at [Icons](https://github.com/gokcehan/lf/wiki/Icons) wiki page for [lf](https://github.com/gokcehan/lf)
