### ISSUE TITLE
[Solved] Cannot get your polybar working in my bspwm system

### ISSUE THREAD

**Issue by garret** [BrodieRobertson/dotfiles#10]
I just watched your last video and wanted to integrate your polybar config. However, it doesn't show anything when launching it on my void linux setup. 

I have two files in my config/polybar folder. One is your config file and the other is a launch script `launch.sh`. This is the content of the `launch.sh`

```
#!/usr/bin/env sh

## Add this to your wm startup file.
# Terminate already running bar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
# Launch bar1 and bar2
polybar main -c ~/.config/polybar/config &
```

While I added this line on my bspwmrc `$HOME/.config/polybar/launch.sh` to autostart. 

When starting the launch.sh I get this output:
```
pgrep: invalid username: -x
error: undefined bar: main
```
And no bar shows at all. I also tried to comment with `;` most of the modules but still nothing. 

Do you know what could be the issue? 

**EDIT:** another question would be how are the variables defined? I mean how polybar knows what for instance `$colors.primary` is? Do you have another file where you have defined such stuff? I was thinking that maybe that is why my bar config is not working. 

**EDIT 2:** I think I figured out the main issue here. I had to substitute `main` with `bar` in my launch script. 

I can see from your `bspwmrc` that you have a `launchpolybar` script though I cannot find this in your dotfiles. 

And in any case still no bar is shown because polybar cannot figure out the result of the variables (like `color0` for instance). Maybe you define such things on your `launchpolybar` script?

**Comment by derektata** [comment]
@garret 

Brodie's launchpolybar script is in his scripts repo, in the polybar folder (link below)
https://github.com/BrodieRobertson/scripts/tree/master/polybar

I recently had an issue where bspwm wouldn't launch my polybar script via the bspwmrc file, but I was able to circumvent that by launching it in my .xinitrc instead. Hope this helps.

**Comment by darklord111** [comment]
@garret 
Polybar gets `$colors.primary`, and other colours from .Xresources.

**Comment by darklord111** [comment]
@garret 
Did you fix your issue? If so, could you close this issue and edit the title and mark it as [solved]?
