### ISSUE TITLE
Missing nvim plugins in 'local' folder

### ISSUE THREAD

**Issue by prakash2033** [BrodieRobertson/dotfiles#2]
Hi Brodie,

Thanks for sharing your dotfiles. I really appreciate it.
I just noticed the nvim plugins are missing as mentioned in vimrc.
The local folder doesn't have nvim folder at all.
If you could add that, it would be great. Thanks

call plug#begin('~/local/share/nvim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'norcalli/nvim-colorizer.lua'
Plug 'junegunn/goyo.vim'
Plug 'tomasiser/vim-code-dark'
Plug 'terryma/vim-multiple-cursors'

**Comment by BrodieRobertson** [comment]
The plugins are all git repositories you'd be much better off redownloading the plugins through Vim-Plug or migrating to some other plugin manager as opposed to embedding a git repo in a git repo.
