### ISSUE TITLE
bspunhide in sxhkdrc

### ISSUE THREAD

**Issue by 11nightfury** [BrodieRobertson/dotfiles#4]
What does `bspunhide` do, I tried looking it up in `man bspwm` but could not find it.

**Comment by terminalforlife** [comment]
If it's anything like the regular `unhide`, it performs a bunch of security checks. Here's the `unhide` short description: `Forensic tool to find hidden processes and ports` I'm guessing the `bsd` part is relating to the BSD systems.

**Comment by 11nightfury** [comment]
okay
